### ISSUE TITLE
Silence the fuzzee's output

### ISSUE THREAD

**Issue by jvoisin** [fuzzitdev/pythonfuzz#11]
It's annoying to have random lines of text displayed in the output out the fuzzer, so it would be nice to silence the fuzzee's output.

- [ ] Silence stdout/stderr
- [ ] Silence [logging]( https://docs.python.org/3/library/logging.html )
- [ ] Silence [warning]( https://docs.python.org/3/library/warnings.html )

**Comment by yevgenypats** [comment]
Good idea. thanks for posting this!
